### ISSUE TITLE
suggestion list

### ISSUE THREAD

**Issue by tovade** [tovade/Andoi#1]
+ here you can leave your suggestions you want to add on the bot

**Comment by XzFrosT** [comment]
Can you made welcome and goodbye with canvas?

**Comment by tovade** [comment]
> Can you made welcome and goodbye with canvas?

would remove custom messages idea though

**Comment by FSCYT** [comment]
Change the Font on the bot-info command. Or make the botinfo command an embed, It doesn't look quite nice now. But thats my opinion.

**Comment by tovade** [comment]
Im rebuilding andoi atm so i will take a look at that

**Comment by sp-sketch** [comment]
make it with quick.db

**Comment by tovade** [comment]
We have switched to mongoDB as quick.db is taking to much storage and installation time.

**Comment by sp-sketch** [comment]
yea but can u create a branch for quick.db pls

**Comment by tovade** [comment]
It takes to much time to make, sorry no

**Comment by sp-sketch** [comment]
aw

**Comment by sp-sketch** [comment]
ok no problem
