### ISSUE TITLE
Embed error in emojis.js command

### ISSUE THREAD

**Issue by Michael7020** [tovade/Andoi#4]
error: (node:25) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
embed: Embed size exceeds maximum size of 6000

i think When emoji are too many the bot throws this error :/

**Comment by tovade** [comment]
Oh yes i will be fixing this soon! Thanks for making an issue!

**Comment by tovade** [comment]
Should be fixed in #1cd34a0 👍

**Comment by tovade** [comment]
Emoji command should be fixed in https://github.com/tovade/Andoi/commit/1cd34a091f60071908e54a1296fff55763337bfc 👍
